import { Sora, Noto_Serif_JP } from 'next/font/google';
import '@/styles/globals.css';

import ThemeProvider from '../utils/ThemeProvider';

import { Header, Footer } from '@/components';

const sora = Sora({
    subsets: ['latin'],
    variable: '--font-sora',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
    display: 'swap',
});

const notoSerifJP = Noto_Serif_JP({
    subsets: ['latin'],
    variable: '--font-noto-serif-jp',
    weight: ['200', '300', '400', '500', '600', '700', '800'],
    display: 'swap',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${sora.variable} ${notoSerifJP.variable} scroll-smooth`}
            suppressHydrationWarning
        >
            <body className="bg-background-light dark:bg-background-dark">
                <ThemeProvider
                    attribute="data-mode"
                    defaultTheme="system"
                    enableSystem
                >
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
