import { Sora, Noto_Serif_JP } from 'next/font/google';
import '@/styles/globals.css';

import { Header, Footer } from '@/components';

const sora = Sora({
    subsets: ['latin'],
    variable: '--font-sora',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
    display: 'swap',
});

const notoSerifJP = Noto_Serif_JP({
    subsets: ['japanese'],
    variable: '--font-noto-serif-jp',
    weight: ['200', '300', '400', '500', '600', '700', '800'],
    display: 'swap',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${sora.variable} ${notoSerifJP.variable} scroll-smooth`}
        >
            <body>
                <Header />
                <main className="bg-background-light transition-colors duration-200 dark:bg-background-dark">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
